version: 0.6.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Previous Visual Studio 2015
environment:
  OLW_CONFIG: Release
  OlwBloggerClientId: 597389294595-271ukaucs8ghmc6c6cnhrbef2c02g5qa.apps.googleusercontent.com
  OlwBloggerClientSecret:
    secure: ym7cbPINJz58iEgVlQCDbRz2W1CTYnxWsvMpMvxHFY4=
  SignClientSecret:
    secure: CHm+63iqVR0ddIHjGwE8nYF2EdUikH5VzCcszekUwptHkCLTuJ3C9ci8fcyox03s
install:
# delete existing vcpkg
  - rmdir C:\Tools\vcpkg /q /s

# install vcpkg again (according to https://github.com/appveyor/ci/issues/1076#issuecomment-322280518)
# use appveyor-issue-2299 branch (https://github.com/Microsoft/vcpkg/issues/2299#issuecomment-349166690)
  - git clone --depth=1 --branch=appveyor-issue-2299 https://github.com/Microsoft/vcpkg C:\Tools\vcpkg
  - cd C:\Tools\vcpkg
  - bootstrap-vcpkg.bat
  - vcpkg integrate install
  - ps: Add-Path 'C:\Tools\vcpkg'
  - cd %appveyor_build_folder%
  
# RDP to check id vspkg target is indeed fixed one
  - ps: test-path C:\windows\WindowsPowerShell\v1.0\powershell.exe
  - where powershell.exe
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  - cmd: nuget install SignClient -Version 0.7.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion
nuget:
  disable_publish_on_pr: true
build_script:  
  - cmd: ./build.cmd
test: off
